-- AgentBridge persistence is control-owned and is bootstrapped by
-- apps/control/src/tools/agent-bridge/agent-bridge-schema.ts.  Keep this
-- historical migration as a no-op so existing migration ledgers retain the
-- version while fresh non-control runtimes do not receive control-only tables.
