export interface EndpointCardDef {
  id: string;
  titleZh: string;
  titleEn: string;
  path: string;
  icon: string;
  iconColor: string;
  iconBg: string;
  badge?: string;
  category: "core" | "media" | "search" | "utility";
  descriptionZh: string;
  descriptionEn: string;
  defaultModel?: string;
  exampleBody?: Record<string, unknown>;
}

export const ENDPOINT_CATEGORIES = [
  { key: "core", titleZh: "核心接口", titleEn: "Core APIs", icon: "hub", color: "#3B82F6" },
  { key: "media", titleZh: "多模态与媒体生成", titleEn: "Multimodal & Media", icon: "perm_media", color: "#8B5CF6" },
  { key: "search", titleZh: "联网与检索", titleEn: "Search & Retrieval", icon: "travel_explore", color: "#06B6D4" },
  { key: "utility", titleZh: "通用与管理端点", titleEn: "Utility & Management", icon: "build", color: "#F59E0B" },
] as const;

export const OFFICIAL_ENDPOINTS: EndpointCardDef[] = [
  // 核心接口
  {
    id: "chat-completions",
    titleZh: "对话补全",
    titleEn: "Chat Completions",
    path: "/v1/chat/completions",
    icon: "chat",
    iconColor: "#3B82F6",
    iconBg: "rgba(59, 130, 246, 0.1)",
    category: "core",
    badge: "OpenAI",
    descriptionZh: "标准对话补全接口，支持流式 SSE、多轮历史、函数调用与多模态输入。",
    descriptionEn: "Standard chat completion endpoint supporting SSE streaming, multi-turn history, function calling and multimodal inputs.",
    defaultModel: "gpt-4o",
    exampleBody: {
      model: "gpt-4o",
      messages: [{ role: "user", content: "Hello! Please briefly introduce the AI Gateway." }],
      stream: false,
    },
  },
  {
    id: "responses",
    titleZh: "结构化响应",
    titleEn: "Structured Responses",
    path: "/v1/responses",
    icon: "code",
    iconColor: "#6366F1",
    iconBg: "rgba(99, 102, 241, 0.1)",
    category: "core",
    descriptionZh: "OpenAI Responses API 规范，支持结构化 JSON Schema 输出约束与自动纠错。",
    descriptionEn: "OpenAI Responses API specification supporting structured JSON Schema output constraints and auto-correction.",
    defaultModel: "gpt-4o",
    exampleBody: {
      model: "gpt-4o",
      input: "Extract contact info: John Doe phone 13800000000",
    },
  },
  {
    id: "completions-legacy",
    titleZh: "传统文本补全",
    titleEn: "Legacy Text Completions",
    path: "/v1/completions",
    icon: "text_fields",
    iconColor: "#F97316",
    iconBg: "rgba(249, 115, 22, 0.1)",
    category: "core",
    descriptionZh: "经典单轮 Prompt 续写与代码补全接口，兼容各类旧版插件与 SDK。",
    descriptionEn: "Classic single-turn prompt completion and code generation endpoint compatible with legacy plugins and SDKs.",
    defaultModel: "gpt-3.5-turbo-instruct",
    exampleBody: {
      model: "gpt-3.5-turbo-instruct",
      prompt: "function fibonacci(n) {",
      max_tokens: 50,
    },
  },
  {
    id: "messages-api",
    titleZh: "Anthropic Messages",
    titleEn: "Anthropic Messages",
    path: "/v1/messages",
    icon: "psychology",
    iconColor: "#A855F7",
    iconBg: "rgba(168, 85, 247, 0.1)",
    category: "core",
    badge: "Anthropic",
    descriptionZh: "原生 Anthropic Messages 协议端点，直接接收 Claude 原生请求并自动路由。",
    descriptionEn: "Native Anthropic Messages protocol endpoint receiving direct Claude requests and automatically routing.",
    defaultModel: "claude-3-7-sonnet-20250219",
    exampleBody: {
      model: "claude-3-7-sonnet-20250219",
      max_tokens: 1024,
      messages: [{ role: "user", content: "Hello Claude!" }],
    },
  },

  // 多模态与媒体生成
  {
    id: "embeddings",
    titleZh: "向量嵌入",
    titleEn: "Vector Embeddings",
    path: "/v1/embeddings",
    icon: "data_array",
    iconColor: "#10B981",
    iconBg: "rgba(16, 185, 129, 0.1)",
    category: "media",
    descriptionZh: "生成高维稠密文本向量，支持多模态向量化、批量处理与维度裁剪。",
    descriptionEn: "Generate high-dimensional dense text embeddings with multimodal support, batching and dimension reduction.",
    defaultModel: "text-embedding-3-small",
    exampleBody: {
      model: "text-embedding-3-small",
      input: ["AI Gateway", "Unified Routing Engine"],
    },
  },
  {
    id: "images-generations",
    titleZh: "图像生成",
    titleEn: "Image Generations",
    path: "/v1/images/generations",
    icon: "image",
    iconColor: "#EC4899",
    iconBg: "rgba(236, 72, 153, 0.1)",
    category: "media",
    descriptionZh: "文本生成图像端点，支持多尺寸、多比例与画质质量参数设置。",
    descriptionEn: "Text-to-image generation endpoint supporting multiple dimensions, aspect ratios and quality presets.",
    defaultModel: "dall-e-3",
    exampleBody: {
      model: "dall-e-3",
      prompt: "A high tech AI server in neon cyberspace",
      size: "1024x1024",
    },
  },
  {
    id: "images-edits",
    titleZh: "图像编辑与重绘",
    titleEn: "Image Edits & Inpainting",
    path: "/v1/images/edits",
    icon: "edit_square",
    iconColor: "#8B5CF6",
    iconBg: "rgba(139, 92, 246, 0.1)",
    category: "media",
    descriptionZh: "基于原始图像与 Mask 遮罩执行区域重绘、扩图与风格迁移。",
    descriptionEn: "Perform regional inpainting, outpainting and style transfer based on source image and mask.",
    defaultModel: "dall-e-2",
  },
  {
    id: "audio-transcriptions",
    titleZh: "语音听写转录",
    titleEn: "Audio Transcriptions",
    path: "/v1/audio/transcriptions",
    icon: "mic",
    iconColor: "#F43F5E",
    iconBg: "rgba(244, 63, 94, 0.1)",
    category: "media",
    descriptionZh: "语音转文本（STT），支持多语言自动识别、时间戳与标点修正。",
    descriptionEn: "Speech-to-text (STT) transcription with multilingual recognition, timestamps and punctuation correction.",
    defaultModel: "whisper-1",
  },
  {
    id: "audio-speech",
    titleZh: "语音合成朗读",
    titleEn: "Text to Speech (TTS)",
    path: "/v1/audio/speech",
    icon: "record_voice_over",
    iconColor: "#06B6D4",
    iconBg: "rgba(6, 182, 212, 0.1)",
    category: "media",
    descriptionZh: "文本转语音（TTS），支持多种拟真人声音色、流式音频与语速微调。",
    descriptionEn: "Text-to-speech (TTS) synthesis supporting natural human-like voices, streaming audio and speed tuning.",
    defaultModel: "tts-1",
    exampleBody: {
      model: "tts-1",
      input: "Welcome to Orbit Gateway!",
      voice: "alloy",
    },
  },

  // 联网与检索
  {
    id: "web-search",
    titleZh: "Web 实时搜索",
    titleEn: "Web Live Search",
    path: "/v1/search",
    icon: "travel_explore",
    iconColor: "#06B6D4",
    iconBg: "rgba(6, 182, 212, 0.1)",
    category: "search",
    descriptionZh: "提供跨搜索引擎（Tavily、Google、Bing 等）的实时网页搜索中继。",
    descriptionEn: "Unified web search relay across Tavily, Google, Bing and other engines.",
    defaultModel: "tavily-search",
    exampleBody: {
      query: "Orbit AI Gateway latest features",
      max_results: 5,
    },
  },

  // 通用与管理端点
  {
    id: "rerank",
    titleZh: "文本重排与精排",
    titleEn: "Text Reranking",
    path: "/v1/rerank",
    icon: "sort",
    iconColor: "#F59E0B",
    iconBg: "rgba(245, 158, 11, 0.1)",
    category: "utility",
    descriptionZh: "重排候选文档与查询的相关性得分，提升 RAG 检索命中精准度。",
    descriptionEn: "Rerank candidate documents based on query semantic relevance to boost RAG retrieval accuracy.",
    defaultModel: "bge-reranker-large",
    exampleBody: {
      model: "bge-reranker-large",
      query: "What is intelligent combo routing?",
      documents: ["Orbit provides weighted, priority and dynamic decision routing", "Today is sunny and good for travel"],
    },
  },
  {
    id: "moderations",
    titleZh: "内容安全合规审核",
    titleEn: "Content Moderation",
    path: "/v1/moderations",
    icon: "shield",
    iconColor: "#FB923C",
    iconBg: "rgba(251, 146, 60, 0.1)",
    category: "utility",
    descriptionZh: "检测输入文本或图像中的违规风险内容与安全合规评分。",
    descriptionEn: "Inspect input text or images for safety compliance, toxicity and content policy violations.",
    defaultModel: "text-moderation-latest",
    exampleBody: {
      input: "Testing content safety and compliance",
    },
  },
  {
    id: "list-models",
    titleZh: "模型列表",
    titleEn: "Model Catalog",
    path: "/v1/models",
    icon: "list",
    iconColor: "#14B8A6",
    iconBg: "rgba(20, 184, 166, 0.1)",
    category: "utility",
    badge: "GET",
    descriptionZh: "获取所有已连接提供商模型、组合虚拟聚合模型与别名清单。",
    descriptionEn: "Retrieve all connected provider models, virtual aggregated combo models and aliases.",
  },
  {
    id: "batch-api",
    titleZh: "批处理任务",
    titleEn: "Batch Processing API",
    path: "/v1/batches",
    icon: "view_list",
    iconColor: "#0D9488",
    iconBg: "rgba(13, 148, 136, 0.1)",
    category: "utility",
    badge: "OpenAI",
    descriptionZh: "异步大批量数据处理接口，支持半价计费模式与任务生命周期轮询。",
    descriptionEn: "Asynchronous high-volume data batch processing supporting discounted pricing and task polling.",
  },
  {
    id: "files-api",
    titleZh: "文件资产管理",
    titleEn: "File Assets Management",
    path: "/v1/files",
    icon: "folder",
    iconColor: "#EAB308",
    iconBg: "rgba(234, 179, 8, 0.1)",
    category: "utility",
    descriptionZh: "上传、检索与删除供微调（Fine-tuning）、批处理或助手调用的文件资产。",
    descriptionEn: "Upload, retrieve and manage files used for fine-tuning, batch processing or assistant tooling.",
  },
];
