/** Database boundary shared by deployable apps. Queries and mutations remain app-owned. */
import {
  ApiKeyEntity,
  AuthLoginAttemptEntity,
  ConfigAuditLogEntity,
  ComboEntity,
  CompressionComboEntity,
  CompressionComboAssignmentEntity,
  KeyGroupEntity,
  GroupModelPermissionEntity,
  KeyGroupMemberEntity,
  ModelComboMappingEntity,
  ApiKeyTokenLimitEntity,
  ModelCapabilityOverrideEntity,
  ModelContextOverrideEntity,
  PluginEntity,
  PlaygroundPresetEntity,
  PluginMetricEntity,
  PluginAnalyticsEntity,
  ProviderConnectionEntity,
  ProviderNodeEntity,
  RegisteredKeyEntity,
  ProviderKeyLimitEntity,
  AccountKeyLimitEntity,
  ProviderPlanEntity,
  ProxyRegistryEntity,
  ProxyAssignmentEntity,
  ProxyScopeRotationEntity,
  ProxySubscriptionEntity,
  SettingsEntity,
  MiddlewareHookEntity,
  TierAssignmentEntity,
  TierConfigEntity,
  WebhookEntity,
  WebhookDeliveryEntity,
  FreeProxyEntity,
  FreeProxySyncErrorEntity,
  ReasoningRoutingRuleEntity,
  QuotaGroupEntity,
  QuotaPoolEntity,
  QuotaAllocationEntity,
  QuotaPoolConnectionEntity,
  QuotaAllocationModelCapEntity,
  GamificationLeaderboardEntity,
  GamificationUserLevelEntity,
  GamificationBadgeDefinitionEntity,
  GamificationUserBadgeEntity,
  GamificationXpAuditLogEntity,
  GamificationTokenLedgerEntity,
  GamificationInviteTokenEntity,
  GamificationCommunityServerEntity,
  EvalSuiteEntity,
  EvalCaseEntity,
  EvalRunEntity,
  ModelAssessmentEntity,
  AssessmentRunEntity,
  ComboHealthEntity,
  HealActionEntity,
  InspectorSessionEntity,
  InspectorSessionRequestEntity,
  InspectorCustomHostEntity,
  RadarFeedCacheEntity,
  RadarSettingsEntity,
  RadarReferralsCacheEntity,
  RadarOffersCacheEntity,
  RadarIntelCacheEntity,
  RadarLocalModelStateEntity,
  DiscoveryResultEntity,
  SkillEntity,
  SkillExecutionEntity,
  SyncTokenEntity,
  UpstreamProxyConfigEntity,
  CliproxyInstanceEntity,
  ServiceNodeEntity,
} from "./entities/control.entity.js";
import {
  AgenticConversationEntity,
  ApiKeyTokenCounterEntity,
  ApiKeyTokenLimitResetLogEntity,
  BatchEntity,
  BatchItemCheckpointEntity,
  ConversationTurnNodeEntity,
  FileEntity,
  ProviderQuotaStateEntity,
  QuotaConsumptionEntity,
  CompressionAnalyticsEntity,
  CompressionEngineBreakdownEntity,
  ReasoningCacheEntity,
  SessionModelHistoryEntity,
  ContextHandoffEntity,
  SemanticCacheEntity,
  CacheMetricEntity,
  RelayTokenEntity,
  RelayRateLimitEntity,
  RelayLogEntity,
  McpToolAuditEntity,
  A2aTaskEntity,
  A2aTaskEventEntity,
  RoutingDecisionEntity,
  CcrBlockEntity,
  CompressionCacheStatsEntity,
  MemoryVecMetaEntity,
  MemoryEntity,
  MiddlewareLogEntity,
} from "./entities/edge.entity.js";
import {
  AuditLogEntity,
  CallLogEntity,
  JobEntity,
  JobRunEntity,
  ProxyLogEntity,
  QuotaSnapshotEntity,
  ProviderQuotaResetEventEntity,
  UsageHistoryEntity,
  HourlyUsageSummaryEntity,
  DailyUsageSummaryEntity,
  ModelCapabilitiesEntity,
  ModelIntelligenceEntity,
} from "./entities/worker.entity.js";
import {
  GatewayMigrationsEntity,
  AgentBridgeStateEntity,
  AgentBridgeMappingEntity,
  AgentBridgeBypassEntity,
  CloudAgentCredentialsEntity,
  CloudAgentTaskEntity,
  ApiKeyContextSourceEntity,
  AutoCandidateOverrideEntity,
  CliAccessTokenEntity,
  ComboAdaptationStateEntity,
  CommandCodeAuthSessionEntity,
  CompressionRunTelemetryEntity,
  ConnectionRuntimeStateEntity,
  DbMetaEntity,
  DomainBudgetEntity,
  DomainBudgetResetLogEntity,
  DomainCostHistoryEntity,
  DomainFallbackChainEntity,
  DomainLockoutStateEntity,
  DomainCircuitBreakerEntity,
  ExclusiveConnectionLeaseEntity,
  PromptTemplateEntity,
  RequestDetailLogEntity,
  SessionAccountAffinityEntity,
  VersionManagerEntity,
} from "./entities/internal.entity.js";
import type { EntityDefinition } from "./entities/definition.js";

export * from "./entities/index.js";
export * from "./gamification.js";
export * from "./proxy.js";

export const GATEWAY_TABLES = {
  gatewayMigrations: "_orbit_migrations",
  settings: "key_value",
  authLoginAttempts: "auth_login_attempts",
  middlewareHooks: "middleware_hooks",
  middlewareLogs: "middleware_logs",
  configAuditLog: "config_audit_log",
  playgroundPresets: "playground_presets",
  pluginMetrics: "plugin_metrics",
  pluginAnalytics: "plugin_analytics",
  providerConnections: "provider_connections",
  providerNodes: "provider_nodes",
  registeredKeys: "registered_keys",
  providerKeyLimits: "provider_key_limits",
  accountKeyLimits: "account_key_limits",
  apiKeys: "api_keys",
  apiKeyGroups: "key_groups",
  groupModelPermissions: "group_model_permissions",
  keyGroupMembers: "key_group_members",
  combos: "combos",
  compressionCombos: "compression_combos",
  compressionComboAssignments: "compression_combo_assignments",
  modelComboMappings: "model_combo_mappings",
  usageHistory: "usage_history",
  hourlyUsageSummary: "hourly_usage_summary",
  dailyUsageSummary: "daily_usage_summary",
  callLogs: "call_logs",
  proxyLogs: "proxy_logs",
  quotaSnapshots: "quota_snapshots",
  auditLogs: "audit_log",
  memories: "memories",
  batches: "batches",
  batchItemCheckpoints: "batch_item_checkpoints",
  files: "files",
  webhooks: "webhooks",
  webhookDeliveries: "webhook_deliveries",
  jobs: "jobs",
  jobRuns: "job_runs",
  agenticConversations: "agentic_conversations",
  conversationTurnNodes: "conversation_turn_nodes",
  apiKeyTokenLimits: "api_key_token_limits",
  apiKeyTokenCounters: "api_key_token_counters",
  apiKeyTokenLimitResetLogs: "api_key_token_limit_reset_logs",
  providerQuotaState: "provider_quota_state",
  providerQuotaResetEvents: "provider_quota_reset_events",
  providerPlans: "provider_plans",
  plugins: "plugins",
  modelCapabilities: "model_capabilities",
  modelIntelligence: "model_intelligence",
  modelContextOverrides: "model_context_overrides",
  modelCapabilityOverrides: "model_capability_overrides",
  tierConfig: "tier_config",
  tierAssignments: "tier_assignments",
  freeProxies: "free_proxies",
  freeProxySyncErrors: "free_proxy_sync_errors",
  proxyRegistry: "proxy_registry",
  proxyAssignments: "proxy_assignments",
  proxyScopeRotation: "proxy_scope_rotation",
  proxySubscriptions: "proxy_subscriptions",
  reasoningRoutingRules: "reasoning_routing_rules",
  quotaGroups: "quota_groups",
  quotaPools: "quota_pools",
  quotaAllocations: "quota_allocations",
  quotaPoolConnections: "quota_pool_connections",
  quotaAllocationModelCaps: "quota_allocation_model_caps",
  gamificationLeaderboard: "leaderboard",
  gamificationUserLevels: "user_levels",
  gamificationBadgeDefinitions: "badge_definitions",
  gamificationUserBadges: "user_badges",
  gamificationXpAuditLog: "xp_audit_log",
  gamificationTokenLedger: "token_ledger",
  gamificationInviteTokens: "invite_tokens",
  gamificationCommunityServers: "community_servers",
  evalSuites: "eval_suites",
  evalCases: "eval_cases",
  evalRuns: "eval_runs",
  modelAssessments: "model_assessments",
  assessmentRuns: "assessment_runs",
  comboHealth: "combo_health",
  healActions: "heal_actions",
  inspectorSessions: "inspector_sessions",
  inspectorSessionRequests: "inspector_session_requests",
  inspectorCustomHosts: "inspector_custom_hosts",
  radarFeedCache: "radar_feed_cache",
  radarSettings: "radar_settings",
  radarReferralsCache: "radar_referrals_cache",
  radarOffersCache: "radar_offers_cache",
  radarIntelCache: "radar_intel_cache",
  radarLocalModelState: "radar_local_model_state",
  discoveryResults: "discovery_results",
  quotaConsumption: "quota_consumption",
  compressionAnalytics: "compression_analytics",
  compressionEngineBreakdown: "compression_engine_breakdown",
  reasoningCache: "reasoning_cache",
  sessionModelHistory: "session_model_history",
  contextHandoffs: "context_handoffs",
  semanticCache: "semantic_cache",
  cacheMetrics: "cache_metrics",
  relayTokens: "relay_tokens",
  relayRateLimits: "relay_rate_limits",
  relayLogs: "relay_logs",
  mcpToolAudit: "mcp_tool_audit",
  skills: "skills",
  skillExecutions: "skill_executions",
  syncTokens: "sync_tokens",
  upstreamProxyConfig: "upstream_proxy_config",
  a2aTasks: "a2a_tasks",
  a2aTaskEvents: "a2a_task_events",
  routingDecisions: "routing_decisions",
  ccrBlocks: "ccr_blocks",
  compressionCacheStats: "compression_cache_stats",
  memoryVecMeta: "memory_vec_meta",
  agentBridgeState: "agent_bridge_state",
  agentBridgeMappings: "agent_bridge_mappings",
  agentBridgeBypass: "agent_bridge_bypass",
  cloudAgentCredentials: "cloud_agent_credentials",
  cloudAgentTasks: "cloud_agent_tasks",
  apiKeyContextSources: "api_key_context_sources",
  autoCandidateOverrides: "auto_candidate_overrides",
  cliAccessTokens: "cli_access_tokens",
  comboAdaptationState: "combo_adaptation_state",
  commandCodeAuthSessions: "command_code_auth_sessions",
  compressionRunTelemetry: "compression_run_telemetry",
  connectionRuntimeState: "connection_runtime_state",
  dbMeta: "db_meta",
  domainBudgets: "domain_budgets",
  domainBudgetResetLogs: "domain_budget_reset_logs",
  domainCostHistory: "domain_cost_history",
  domainFallbackChains: "domain_fallback_chains",
  domainLockoutState: "domain_lockout_state",
  domainCircuitBreakers: "domain_circuit_breakers",
  exclusiveConnectionLeases: "exclusive_connection_leases",
  promptTemplates: "prompt_templates",
  requestDetailLogs: "request_detail_logs",
  sessionAccountAffinity: "session_account_affinity",
  versionManager: "version_manager",
  cliproxyInstances: "cliproxy_instances",
  serviceNodes: "service_nodes",
} as const;

export type GatewayTable = (typeof GATEWAY_TABLES)[keyof typeof GATEWAY_TABLES];

export interface TableRef {
  table: GatewayTable;
  owner: "control" | "gateway" | "realtime" | "worker";
  access: "read" | "write" | "read-write";
}

/**
 * Explicit ownership map used by architecture checks and code review. A
 * table can be read by several apps, but writes have one operational owner.
 */
export const TABLE_OWNERSHIP: readonly TableRef[] = [
  { table: GATEWAY_TABLES.gatewayMigrations, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.settings, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.authLoginAttempts, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.middlewareHooks, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.middlewareLogs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.configAuditLog, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.playgroundPresets, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.pluginMetrics, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.pluginAnalytics, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.providerConnections, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.providerNodes, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.registeredKeys, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.providerKeyLimits, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.accountKeyLimits, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeys, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeyGroups, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.groupModelPermissions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.keyGroupMembers, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.combos, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.compressionCombos, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.compressionComboAssignments, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.modelComboMappings, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.usageHistory, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.hourlyUsageSummary, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.dailyUsageSummary, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.callLogs, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.proxyLogs, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.quotaSnapshots, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.auditLogs, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.memories, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.batches, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.batchItemCheckpoints, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.files, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.webhooks, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.webhookDeliveries, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.jobs, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.jobRuns, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.agenticConversations, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.conversationTurnNodes, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeyTokenLimits, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeyTokenCounters, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeyTokenLimitResetLogs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.providerQuotaState, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.providerQuotaResetEvents, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.providerPlans, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.plugins, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.modelCapabilities, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.modelIntelligence, owner: "worker", access: "read-write" },
  { table: GATEWAY_TABLES.modelContextOverrides, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.modelCapabilityOverrides, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.tierConfig, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.tierAssignments, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.freeProxies, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.freeProxySyncErrors, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.proxyRegistry, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.proxyAssignments, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.proxyScopeRotation, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.proxySubscriptions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.reasoningRoutingRules, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaGroups, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaPools, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaAllocations, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaPoolConnections, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaAllocationModelCaps, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationLeaderboard, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationUserLevels, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationBadgeDefinitions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationUserBadges, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationXpAuditLog, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationTokenLedger, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationInviteTokens, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.gamificationCommunityServers, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.evalSuites, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.evalCases, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.evalRuns, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.modelAssessments, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.assessmentRuns, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.comboHealth, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.healActions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.inspectorSessions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.inspectorSessionRequests, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.inspectorCustomHosts, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarFeedCache, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarSettings, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarReferralsCache, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarOffersCache, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarIntelCache, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.radarLocalModelState, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.discoveryResults, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.quotaConsumption, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.compressionAnalytics, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.compressionEngineBreakdown, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.reasoningCache, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.sessionModelHistory, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.contextHandoffs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.semanticCache, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.cacheMetrics, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.relayTokens, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.relayRateLimits, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.relayLogs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.mcpToolAudit, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.skills, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.skillExecutions, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.syncTokens, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.upstreamProxyConfig, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.a2aTasks, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.a2aTaskEvents, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.routingDecisions, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.ccrBlocks, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.compressionCacheStats, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.memoryVecMeta, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.agentBridgeState, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.agentBridgeMappings, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.agentBridgeBypass, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.cloudAgentCredentials, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.cloudAgentTasks, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.apiKeyContextSources, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.autoCandidateOverrides, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.cliAccessTokens, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.comboAdaptationState, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.commandCodeAuthSessions, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.compressionRunTelemetry, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.connectionRuntimeState, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.dbMeta, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.domainBudgets, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.domainBudgetResetLogs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.domainCostHistory, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.domainFallbackChains, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.domainLockoutState, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.domainCircuitBreakers, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.exclusiveConnectionLeases, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.promptTemplates, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.requestDetailLogs, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.sessionAccountAffinity, owner: "gateway", access: "read-write" },
  { table: GATEWAY_TABLES.versionManager, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.cliproxyInstances, owner: "control", access: "read-write" },
  { table: GATEWAY_TABLES.serviceNodes, owner: "control", access: "read-write" },
];

/**
 * Canonical physical entities for every table whose structure is governed by
 * the deployable apps.  The mapped keys intentionally follow the public
 * vocabulary above; each entity keeps a Nest/ORM-style stable `entityName`
 * and an exact SQLite `tableName`.
 */
export const GATEWAY_ENTITIES = {
  gatewayMigrations: GatewayMigrationsEntity,
  settings: SettingsEntity,
  authLoginAttempts: AuthLoginAttemptEntity,
  middlewareHooks: MiddlewareHookEntity,
  middlewareLogs: MiddlewareLogEntity,
  configAuditLog: ConfigAuditLogEntity,
  playgroundPresets: PlaygroundPresetEntity,
  pluginMetrics: PluginMetricEntity,
  pluginAnalytics: PluginAnalyticsEntity,
  providerConnections: ProviderConnectionEntity,
  providerNodes: ProviderNodeEntity,
  registeredKeys: RegisteredKeyEntity,
  providerKeyLimits: ProviderKeyLimitEntity,
  accountKeyLimits: AccountKeyLimitEntity,
  apiKeys: ApiKeyEntity,
  apiKeyGroups: KeyGroupEntity,
  groupModelPermissions: GroupModelPermissionEntity,
  keyGroupMembers: KeyGroupMemberEntity,
  combos: ComboEntity,
  compressionCombos: CompressionComboEntity,
  compressionComboAssignments: CompressionComboAssignmentEntity,
  modelComboMappings: ModelComboMappingEntity,
  usageHistory: UsageHistoryEntity,
  hourlyUsageSummary: HourlyUsageSummaryEntity,
  dailyUsageSummary: DailyUsageSummaryEntity,
  callLogs: CallLogEntity,
  proxyLogs: ProxyLogEntity,
  quotaSnapshots: QuotaSnapshotEntity,
  auditLogs: AuditLogEntity,
  memories: MemoryEntity,
  batches: BatchEntity,
  batchItemCheckpoints: BatchItemCheckpointEntity,
  files: FileEntity,
  webhooks: WebhookEntity,
  webhookDeliveries: WebhookDeliveryEntity,
  jobs: JobEntity,
  jobRuns: JobRunEntity,
  agenticConversations: AgenticConversationEntity,
  conversationTurnNodes: ConversationTurnNodeEntity,
  apiKeyTokenLimits: ApiKeyTokenLimitEntity,
  apiKeyTokenCounters: ApiKeyTokenCounterEntity,
  apiKeyTokenLimitResetLogs: ApiKeyTokenLimitResetLogEntity,
  providerQuotaState: ProviderQuotaStateEntity,
  providerQuotaResetEvents: ProviderQuotaResetEventEntity,
  providerPlans: ProviderPlanEntity,
  plugins: PluginEntity,
  modelCapabilities: ModelCapabilitiesEntity,
  modelIntelligence: ModelIntelligenceEntity,
  modelContextOverrides: ModelContextOverrideEntity,
  modelCapabilityOverrides: ModelCapabilityOverrideEntity,
  tierConfig: TierConfigEntity,
  tierAssignments: TierAssignmentEntity,
  freeProxies: FreeProxyEntity,
  freeProxySyncErrors: FreeProxySyncErrorEntity,
  proxyRegistry: ProxyRegistryEntity,
  proxyAssignments: ProxyAssignmentEntity,
  proxyScopeRotation: ProxyScopeRotationEntity,
  proxySubscriptions: ProxySubscriptionEntity,
  reasoningRoutingRules: ReasoningRoutingRuleEntity,
  quotaGroups: QuotaGroupEntity,
  quotaPools: QuotaPoolEntity,
  quotaAllocations: QuotaAllocationEntity,
  quotaPoolConnections: QuotaPoolConnectionEntity,
  quotaAllocationModelCaps: QuotaAllocationModelCapEntity,
  gamificationLeaderboard: GamificationLeaderboardEntity,
  gamificationUserLevels: GamificationUserLevelEntity,
  gamificationBadgeDefinitions: GamificationBadgeDefinitionEntity,
  gamificationUserBadges: GamificationUserBadgeEntity,
  gamificationXpAuditLog: GamificationXpAuditLogEntity,
  gamificationTokenLedger: GamificationTokenLedgerEntity,
  gamificationInviteTokens: GamificationInviteTokenEntity,
  gamificationCommunityServers: GamificationCommunityServerEntity,
  evalSuites: EvalSuiteEntity,
  evalCases: EvalCaseEntity,
  evalRuns: EvalRunEntity,
  modelAssessments: ModelAssessmentEntity,
  assessmentRuns: AssessmentRunEntity,
  comboHealth: ComboHealthEntity,
  healActions: HealActionEntity,
  inspectorSessions: InspectorSessionEntity,
  inspectorSessionRequests: InspectorSessionRequestEntity,
  inspectorCustomHosts: InspectorCustomHostEntity,
  radarFeedCache: RadarFeedCacheEntity,
  radarSettings: RadarSettingsEntity,
  radarReferralsCache: RadarReferralsCacheEntity,
  radarOffersCache: RadarOffersCacheEntity,
  radarIntelCache: RadarIntelCacheEntity,
  radarLocalModelState: RadarLocalModelStateEntity,
  discoveryResults: DiscoveryResultEntity,
  quotaConsumption: QuotaConsumptionEntity,
  compressionAnalytics: CompressionAnalyticsEntity,
  compressionEngineBreakdown: CompressionEngineBreakdownEntity,
  reasoningCache: ReasoningCacheEntity,
  sessionModelHistory: SessionModelHistoryEntity,
  contextHandoffs: ContextHandoffEntity,
  semanticCache: SemanticCacheEntity,
  cacheMetrics: CacheMetricEntity,
  relayTokens: RelayTokenEntity,
  relayRateLimits: RelayRateLimitEntity,
  relayLogs: RelayLogEntity,
  mcpToolAudit: McpToolAuditEntity,
  skills: SkillEntity,
  skillExecutions: SkillExecutionEntity,
  syncTokens: SyncTokenEntity,
  upstreamProxyConfig: UpstreamProxyConfigEntity,
  a2aTasks: A2aTaskEntity,
  a2aTaskEvents: A2aTaskEventEntity,
  routingDecisions: RoutingDecisionEntity,
  ccrBlocks: CcrBlockEntity,
  compressionCacheStats: CompressionCacheStatsEntity,
  memoryVecMeta: MemoryVecMetaEntity,
  agentBridgeState: AgentBridgeStateEntity,
  agentBridgeMappings: AgentBridgeMappingEntity,
  agentBridgeBypass: AgentBridgeBypassEntity,
  cloudAgentCredentials: CloudAgentCredentialsEntity,
  cloudAgentTasks: CloudAgentTaskEntity,
  apiKeyContextSources: ApiKeyContextSourceEntity,
  autoCandidateOverrides: AutoCandidateOverrideEntity,
  cliAccessTokens: CliAccessTokenEntity,
  comboAdaptationState: ComboAdaptationStateEntity,
  commandCodeAuthSessions: CommandCodeAuthSessionEntity,
  compressionRunTelemetry: CompressionRunTelemetryEntity,
  connectionRuntimeState: ConnectionRuntimeStateEntity,
  dbMeta: DbMetaEntity,
  domainBudgets: DomainBudgetEntity,
  domainBudgetResetLogs: DomainBudgetResetLogEntity,
  domainCostHistory: DomainCostHistoryEntity,
  domainFallbackChains: DomainFallbackChainEntity,
  domainLockoutState: DomainLockoutStateEntity,
  domainCircuitBreakers: DomainCircuitBreakerEntity,
  exclusiveConnectionLeases: ExclusiveConnectionLeaseEntity,
  promptTemplates: PromptTemplateEntity,
  requestDetailLogs: RequestDetailLogEntity,
  sessionAccountAffinity: SessionAccountAffinityEntity,
  versionManager: VersionManagerEntity,
  cliproxyInstances: CliproxyInstanceEntity,
  serviceNodes: ServiceNodeEntity,
} satisfies Record<keyof typeof GATEWAY_TABLES, EntityDefinition>;

/** Runtime guard used by architecture checks and tests. */
export function assertGatewayEntities(): void {
  const tableEntries = Object.entries(GATEWAY_TABLES) as Array<[
    keyof typeof GATEWAY_TABLES,
    GatewayTable,
  ]>;
  const tableKeys = new Set(tableEntries.map(([key]) => key));
  const physicalTables = new Set<GatewayTable>();
  for (const [key, table] of tableEntries) {
    if (physicalTables.has(table)) {
      throw new Error(`Duplicate physical table in GATEWAY_TABLES: ${table}`);
    }
    physicalTables.add(table);
    if (!GATEWAY_ENTITIES[key]) {
      throw new Error(`Missing entity catalog entry for table key: ${key}`);
    }
  }

  const ownershipByTable = new Map<GatewayTable, TableRef>();
  for (const ref of TABLE_OWNERSHIP) {
    if (!physicalTables.has(ref.table)) {
      throw new Error(`Ownership references unknown gateway table: ${ref.table}`);
    }
    if (ownershipByTable.has(ref.table)) {
      throw new Error(`Duplicate ownership declaration for table: ${ref.table}`);
    }
    ownershipByTable.set(ref.table, ref);
  }
  if (ownershipByTable.size !== physicalTables.size) {
    const missingOwnership = [...physicalTables].filter((table) => !ownershipByTable.has(table));
    throw new Error(`Missing ownership declaration for tables: ${missingOwnership.join(", ")}`);
  }

  const entityNames = new Set<string>();
  for (const [key, entity] of Object.entries(GATEWAY_ENTITIES) as Array<[
    keyof typeof GATEWAY_TABLES,
    EntityDefinition,
  ]>) {
    if (!tableKeys.has(key)) {
      throw new Error(`Entity catalog contains unknown table key: ${key}`);
    }
    if (entity.tableName !== GATEWAY_TABLES[key]) {
      throw new Error(`Entity ${key} maps to ${entity.tableName}, expected ${GATEWAY_TABLES[key]}`);
    }
    if (entityNames.has(entity.entityName)) {
      throw new Error(`Duplicate entityName in gateway catalog: ${entity.entityName}`);
    }
    entityNames.add(entity.entityName);
    const columnNames = new Set<string>();
    for (const item of entity.columns) {
      if (!item.name.trim()) throw new Error(`Entity ${key} contains an unnamed column`);
      if (columnNames.has(item.name)) throw new Error(`Entity ${key} contains duplicate column: ${item.name}`);
      columnNames.add(item.name);
    }
    const ownership = ownershipByTable.get(entity.tableName);
    if (!ownership || ownership.owner !== entity.owner) {
      throw new Error(`Entity ${key} has no matching table ownership declaration`);
    }
    if (entity.columns.length === 0) throw new Error(`Entity ${key} has no columns`);
  }
}

export function tableOwner(table: GatewayTable): TableRef["owner"] {
  const ref = TABLE_OWNERSHIP.find((item) => item.table === table);
  if (!ref) throw new Error(`Unknown gateway table: ${table}`);
  return ref.owner;
}
