export const CLAUDE_CONFIG: any;
export const CODEX_CONFIG: any;
export const QODER_CONFIG: any;
export const CODEBUDDY_CN_CONFIG: any;
export const GROK_CLI_CONFIG: any;
export const GROK_BUILD_OAUTH_CONFIG: any;
export const XAI_OAUTH_CONFIG: any;
export const OPENFERENCE_CONFIG: any;
export const KIMI_CODING_CONFIG: any;
export const KILOCODE_CONFIG: any;
export const CLINE_CONFIG: any;
export const ANTIGRAVITY_CONFIG: any;
export const AGY_CONFIG: any;
export const OPENAI_CONFIG: any;
export const GITHUB_CONFIG: any;
export const GHE_COPILOT_CONFIG: any;
export const GITLAB_DUO_CONFIG: any;
export const AWS_REGION_PATTERN: RegExp;
export function assertValidAwsRegion(region: string): void;
export const KIRO_CONFIG: any;
export const CURSOR_CONFIG: any;
export const TRAE_CONFIG: any;
export const DEVIN_DESKTOP_CONFIG: any;
export const ZED_CONFIG: any;
export const ZED_HOSTED_CONFIG: any;
export const OAUTH_TIMEOUT: number;
export const PROVIDERS: Record<string, any>;
