export {
  addProxyToScopePool,
  assignProxyToScope,
  bulkAssignProxyToScope,
  createProxy,
  createProxyAndAssign,
  deleteProxyById,
  extractRelayAuth,
  getProxyAssignments,
  getProxyHealthStats,
  getScopeProxyPool,
  getScopeRotationStrategy,
  isRelayAuthMissing,
  isRelayProxyType,
  listProxies,
  migrateLegacyProxyConfigToRegistry,
  redactProxySecrets,
  relayRepairMode,
  removeProxyFromScopePool,
  resolveProxyForScopeFromRegistry,
  setScopeRotationStrategy,
  updateProxy,
  updateProxyAndAssign,
  upsertProxy,
} from "../lib/db/proxies.js";
