import { getDbInstance } from "./core.ts";
export interface A2ATaskHistoryRow {id:string;state:string;skill_id:string|null;input_json:string|null;output_json:string|null;api_key_id:string|null;created_at:string;updated_at:string;completed_at:string|null}
export interface A2ATaskHistoryEventRow {event_type:string;data_json:string|null;created_at:string}
export interface A2AHistoryFilter {from?:string;to?:string;skill?:string;state?:string;owner?:string;limit:number;offset:number}
export interface UpsertA2ATaskInput {id:string;state:string;skillId:string|null;inputJson:string|null;outputJson:string|null;apiKeyId:string|null;createdAt:string;updatedAt:string;completedAt:string|null}
function where(f:Omit<A2AHistoryFilter,"limit"|"offset">){const clauses:string[]=[];const params:Record<string,unknown>={};if(f.from){clauses.push("created_at >= @from");params.from=f.from}if(f.to){clauses.push("created_at <= @to");params.to=f.to}if(f.skill){clauses.push("skill_id = @skill");params.skill=f.skill}if(f.state){clauses.push("state = @state");params.state=f.state}if(f.owner!==undefined){clauses.push("(api_key_id IS NULL OR api_key_id = @owner)");params.owner=f.owner}return {sql:clauses.length?`WHERE ${clauses.join(" AND ")}`:"",params};}
export function upsertA2ATask(row:UpsertA2ATaskInput){getDbInstance().prepare(`INSERT INTO a2a_tasks(id,state,skill_id,input_json,output_json,api_key_id,created_at,updated_at,completed_at) VALUES(@id,@state,@skillId,@inputJson,@outputJson,@apiKeyId,@createdAt,@updatedAt,@completedAt) ON CONFLICT(id) DO UPDATE SET state=excluded.state,output_json=excluded.output_json,updated_at=excluded.updated_at,completed_at=excluded.completed_at`).run(row);}
export function appendA2ATaskEvent(taskId:string,eventType:string,dataJson?:string){getDbInstance().prepare("INSERT INTO a2a_task_events(task_id,event_type,data_json) VALUES(?,?,?)").run(taskId,eventType,dataJson??null);}
export function listA2ATaskEvents(taskId:string){return getDbInstance().prepare("SELECT event_type,data_json,created_at FROM a2a_task_events WHERE task_id=? ORDER BY id").all(taskId) as A2ATaskHistoryEventRow[];}
export function listA2ATaskHistory(f:A2AHistoryFilter){const built=where(f);const total=getDbInstance().prepare(`SELECT COUNT(*) count FROM a2a_tasks ${built.sql}`).get(built.params) as {count:number};const rows=getDbInstance().prepare(`SELECT id,state,skill_id,input_json,output_json,api_key_id,created_at,updated_at,completed_at FROM a2a_tasks ${built.sql} ORDER BY created_at DESC LIMIT @limit OFFSET @offset`).all({...built.params,limit:f.limit,offset:f.offset}) as A2ATaskHistoryRow[];return {rows,total:Number(total.count)};}
export function purgeA2AHistory(retentionDays:number){const db=getDbInstance();return db.transaction((days:number)=>{db.prepare("DELETE FROM a2a_task_events WHERE task_id IN (SELECT id FROM a2a_tasks WHERE created_at < datetime('now','-' || @days || ' days'))").run({days});return db.prepare("DELETE FROM a2a_tasks WHERE created_at < datetime('now','-' || @days || ' days')").run({days}).changes;})(retentionDays);}
