/**
 * Stable, transport-neutral inventory of CLI capabilities consumed by skill
 * generation and other discovery surfaces. This is deliberately data-only: it
 * must not inspect an application checkout or depend on process.cwd().
 */

export const CLI_SKILL_FAMILIES = [
  "cli-serve",
  "cli-health",
  "cli-providers",
  "cli-keys",
  "cli-models",
  "cli-chat",
  "cli-routing",
  "cli-resilience",
  "cli-compression",
  "cli-contexts",
  "cli-cost-usage",
  "cli-mcp",
  "cli-a2a",
  "cli-tunnel",
  "cli-backup-sync",
  "cli-policy-audit",
  "cli-batches",
  "cli-eval",
  "cli-plugins-skills",
  "cli-setup"
] as const;

export type CliSkillFamily = (typeof CLI_SKILL_FAMILIES)[number];

export interface CliCapability {
  /** Full Commander hierarchy. Arguments remain attached to their command segment. */
  readonly path: readonly [string, ...string[]];
  readonly family: CliSkillFamily;
  readonly description: string;
  readonly flags: readonly string[];
}

export const CLI_CAPABILITY_MANIFEST = [
  { path: ["serve"], family: "cli-serve", description: "", flags: ["--port <port>","--no-open","--daemon","--log","--no-recovery","--max-restarts <n>","--tray","--no-tray","--tls-cert <path>","--tls-key <path>"] },
  { path: ["dashboard"], family: "cli-serve", description: "", flags: ["--url","--port <port>","--tui"] },
  { path: ["stop"], family: "cli-serve", description: "", flags: [] },
  { path: ["restart"], family: "cli-serve", description: "", flags: ["--port <port>"] },
  { path: ["health"], family: "cli-health", description: "", flags: ["-v, --verbose","--json","--alerts-only"] },
  { path: ["health","components"], family: "cli-health", description: "List health components and their status", flags: ["--alerts-only"] },
  { path: ["health","watch"], family: "cli-health", description: "Live dashboard — refresh every N seconds", flags: ["--interval <s>"] },
  { path: ["status"], family: "cli-health", description: "Show Orbit status dashboard", flags: ["-v, --verbose"] },
  { path: ["doctor"], family: "cli-health", description: "", flags: ["--no-liveness","--host <host>","--liveness-url <url>"] },
  { path: ["providers"], family: "cli-providers", description: "", flags: [] },
  { path: ["providers","available"], family: "cli-providers", description: "Show available providers in the Orbit catalog", flags: ["--json","--search <query>","-q, --q <query>","--category <category>"] },
  { path: ["providers","list"], family: "cli-providers", description: "List configured provider connections", flags: ["--json"] },
  { path: ["providers","test <idOrName>"], family: "cli-providers", description: "Test a configured provider connection", flags: ["--json"] },
  { path: ["providers","test-all"], family: "cli-providers", description: "Test all active provider connections", flags: ["--json"] },
  { path: ["providers","validate"], family: "cli-providers", description: "Validate local provider configuration without calling upstream", flags: ["--json"] },
  { path: ["providers","rotate <idOrName>"], family: "cli-providers", description: "", flags: ["--new-key <key>","--from-env <VAR>","--oauth","--yes","--skip-test","--dry-run"] },
  { path: ["providers","status"], family: "cli-providers", description: "", flags: ["--provider <name>","--json"] },
  { path: ["providers","metrics"], family: "cli-providers", description: "", flags: ["--provider <id>","--connection-id <id>","--period <p>","--metric <m>","--sort-by <field>","--limit <n>","--watch","--compare <list>"] },
  { path: ["providers","metric <connectionId> <metric>"], family: "cli-providers", description: "", flags: ["--period <p>"] },
  { path: ["provider [subcommand]"], family: "cli-providers", description: "Manage provider connections (use 'providers' for the full interface)", flags: [] },
  { path: ["test [provider] [model]"], family: "cli-providers", description: "", flags: ["--all-providers","--json","--latency","--repeat <n>","--compare <models>","--save <path>"] },
  { path: ["keys"], family: "cli-keys", description: "", flags: [] },
  { path: ["keys","add <provider> [apiKey]"], family: "cli-keys", description: "", flags: ["--stdin"] },
  { path: ["keys","list"], family: "cli-keys", description: "", flags: ["--json"] },
  { path: ["keys","remove <provider>"], family: "cli-keys", description: "", flags: ["--yes"] },
  { path: ["keys","regenerate <id>"], family: "cli-keys", description: "", flags: ["--yes"] },
  { path: ["keys","revoke <id>"], family: "cli-keys", description: "", flags: ["--yes"] },
  { path: ["keys","reveal <id>"], family: "cli-keys", description: "", flags: [] },
  { path: ["keys","usage <id>"], family: "cli-keys", description: "", flags: ["--limit <n>"] },
  { path: ["keys","policy"], family: "cli-keys", description: "", flags: [] },
  { path: ["keys","policy","show <id>"], family: "cli-keys", description: "", flags: [] },
  { path: ["keys","policy","set <id>"], family: "cli-keys", description: "", flags: ["--rate-limit <n>","--max-cost <n>","--allowed-models <list>"] },
  { path: ["keys","expiration"], family: "cli-keys", description: "", flags: [] },
  { path: ["keys","expiration","list"], family: "cli-keys", description: "", flags: ["--days <n>","--json"] },
  { path: ["keys","rotate <id>"], family: "cli-keys", description: "", flags: ["--grace-period <ms>","--yes"] },
  { path: ["oauth"], family: "cli-keys", description: "", flags: [] },
  { path: ["oauth","providers"], family: "cli-keys", description: "", flags: [] },
  { path: ["oauth","start"], family: "cli-keys", description: "", flags: ["--provider <id>","--no-browser","--import-from-system","--social <s>","--timeout <ms>"] },
  { path: ["oauth","status"], family: "cli-keys", description: "", flags: ["--provider <id>"] },
  { path: ["oauth","revoke"], family: "cli-keys", description: "", flags: ["--provider <id>","--connection-id <id>","--yes"] },
  { path: ["models [provider]"], family: "cli-models", description: "", flags: ["--search <query>","--json"] },
  { path: ["chat [prompt]"], family: "cli-chat", description: "", flags: ["--file <path>","--stdin","-s, --system <prompt>","-m, --model <id>","--max-tokens <n>","--temperature <t>","--top-p <p>","--reasoning-effort <level>","--thinking-budget <tokens>","--combo <name>","--responses-api","--stream","--no-history"] },
  { path: ["stream [prompt]"], family: "cli-chat", description: "", flags: ["--file <path>","--stdin","-m, --model <id>","-s, --system <prompt>","--combo <name>","--max-tokens <n>","--responses-api","--raw","--debug","--save <path>"] },
  { path: ["repl"], family: "cli-chat", description: "", flags: ["-m, --model <id>","--combo <name>","-s, --system <prompt>","--resume <session>"] },
  { path: ["combo","suggest"], family: "cli-routing", description: "", flags: ["--task <description>","--max-cost <usd>","--max-latency-ms <ms>","--weights <json>","--top <n>","--explain","--switch"] },
  { path: ["combo"], family: "cli-routing", description: "", flags: [] },
  { path: ["combo","list"], family: "cli-routing", description: "List configured routing combos", flags: ["--json"] },
  { path: ["combo","switch <name>"], family: "cli-routing", description: "Activate a routing combo", flags: [] },
  { path: ["combo","create <name>"], family: "cli-routing", description: "Create a new routing combo", flags: ["--models <spec>","--model <spec>"] },
  { path: ["combo","delete <name>"], family: "cli-routing", description: "Delete a routing combo", flags: ["--yes"] },
  { path: ["resilience"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","status"], family: "cli-resilience", description: "", flags: ["--provider <p>"] },
  { path: ["resilience","breakers"], family: "cli-resilience", description: "", flags: ["--provider <p>"] },
  { path: ["resilience","cooldowns"], family: "cli-resilience", description: "", flags: ["--provider <p>","--connection-id <id>"] },
  { path: ["resilience","lockouts"], family: "cli-resilience", description: "", flags: ["--provider <p>","--model <m>"] },
  { path: ["resilience","reset"], family: "cli-resilience", description: "", flags: ["--provider <p>","--connection-id <id>","--model <m>","--all-cooldowns","--yes"] },
  { path: ["resilience","profile"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","profile","show"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","profile","set"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","config"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","config","show"], family: "cli-resilience", description: "", flags: [] },
  { path: ["resilience","config","set"], family: "cli-resilience", description: "", flags: ["--threshold <n>","--reset-timeout <ms>","--base-cooldown <ms>"] },
  { path: ["quota"], family: "cli-resilience", description: "", flags: ["--provider <id>","--json"] },
  { path: ["quota","status"], family: "cli-resilience", description: "Show truthful Orbit gateway, quota, pool, and circuit state", flags: [] },
  { path: ["quota","preview"], family: "cli-resilience", description: "Preview allocation enforcement without an upstream request", flags: ["--api-key-id <id>","--pool-id <id>","--tokens <n>"] },
  { path: ["quota","ensure <json>"], family: "cli-resilience", description: "Idempotently create or update a quota pool from a JSON object", flags: [] },
  { path: ["compression"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","status"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","configure"], family: "cli-compression", description: "", flags: ["--engine <e>","--caveman-aggressiveness <n>","--rtk-budget <n>","--language-pack <p>"] },
  { path: ["compression","engine"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","engine","set <name>"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","engine","get"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","combos"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","combos","list"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","combos","stats"], family: "cli-compression", description: "", flags: ["--period <p>"] },
  { path: ["compression","rules"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","rules","list"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","rules","add"], family: "cli-compression", description: "", flags: ["--pattern <p>","--action <a>","--replacement <r>"] },
  { path: ["compression","rules","remove <id>"], family: "cli-compression", description: "", flags: ["--yes"] },
  { path: ["compression","language-packs"], family: "cli-compression", description: "", flags: [] },
  { path: ["compression","preview"], family: "cli-compression", description: "", flags: ["--file <path>"] },
  { path: ["context-eng"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","analytics"], family: "cli-contexts", description: "", flags: ["--period <p>"] },
  { path: ["context-eng","caveman"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","caveman","config"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","caveman","config","show"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","caveman","config","set"], family: "cli-contexts", description: "", flags: ["--aggressiveness <n>","--max-shrink-pct <n>","--preserve-tags <list>"] },
  { path: ["context-eng","rtk"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","rtk","config"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","rtk","config","show"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","rtk","config","set"], family: "cli-contexts", description: "", flags: ["--token-budget <n>","--reserve-pct <n>"] },
  { path: ["context-eng","rtk","filters"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","rtk","filters","list"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","rtk","filters","add"], family: "cli-contexts", description: "", flags: ["--pattern <p>","--priority <n>","--action <a>"] },
  { path: ["context-eng","rtk","filters","remove <id>"], family: "cli-contexts", description: "", flags: ["--yes"] },
  { path: ["context-eng","rtk","test"], family: "cli-contexts", description: "", flags: ["--file <path>"] },
  { path: ["context-eng","rtk","raw-output <id>"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","combos"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","combos","list"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","combos","get <id>"], family: "cli-contexts", description: "", flags: [] },
  { path: ["context-eng","combos","assignments <id>"], family: "cli-contexts", description: "", flags: [] },
  { path: ["contexts"], family: "cli-contexts", description: "", flags: [] },
  { path: ["contexts","list"], family: "cli-contexts", description: "List all contexts", flags: [] },
  { path: ["contexts","add <name>"], family: "cli-contexts", description: "Add a new context", flags: ["--url <u>","--api-key <k>","--api-key-stdin","--access-token <t>","--access-token-stdin","--scope <s>","--description <d>"] },
  { path: ["contexts","use <name>"], family: "cli-contexts", description: "Switch active context", flags: [] },
  { path: ["contexts","current"], family: "cli-contexts", description: "Show the active context (server, auth, scope)", flags: ["--name-only"] },
  { path: ["contexts","show <name>"], family: "cli-contexts", description: "Show context details", flags: [] },
  { path: ["contexts","remove <name>"], family: "cli-contexts", description: "Remove a context", flags: ["--yes"] },
  { path: ["contexts","rename <old> <new>"], family: "cli-contexts", description: "Rename a context", flags: [] },
  { path: ["contexts","export"], family: "cli-contexts", description: "Export contexts to JSON", flags: ["--out <path>","--no-secrets"] },
  { path: ["contexts","import <file>"], family: "cli-contexts", description: "Import contexts from a JSON file", flags: ["--merge"] },
  { path: ["contexts","migrate"], family: "cli-contexts", description: "Move legacy plaintext context credentials to the OS keychain", flags: ["--yes"] },
  { path: ["sessions"], family: "cli-contexts", description: "", flags: [] },
  { path: ["sessions","list"], family: "cli-contexts", description: "", flags: ["--user <u>","--kind <k>","--active","--limit <n>"] },
  { path: ["sessions","show <sessionId>"], family: "cli-contexts", description: "", flags: [] },
  { path: ["sessions","expire <sessionId>"], family: "cli-contexts", description: "", flags: ["--yes"] },
  { path: ["sessions","expire-all"], family: "cli-contexts", description: "", flags: ["--user <u>","--yes"] },
  { path: ["sessions","current"], family: "cli-contexts", description: "", flags: [] },
  { path: ["cost"], family: "cli-cost-usage", description: "", flags: ["--period <range>","--since <date>","--until <date>","--group-by <field>","--api-key <key>","--limit <n>"] },
  { path: ["usage"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["usage","analytics"], family: "cli-cost-usage", description: "", flags: ["--period <range>","--provider <id>"] },
  { path: ["usage","budget"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["usage","budget","list"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["usage","budget","get [scope]"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["usage","budget","set <amount>"], family: "cli-cost-usage", description: "", flags: ["--scope <s>","--period <p>"] },
  { path: ["usage","budget","reset [scope]"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["usage","quota"], family: "cli-cost-usage", description: "", flags: ["--provider <id>","--check"] },
  { path: ["usage","logs"], family: "cli-cost-usage", description: "", flags: ["--limit <n>","--search <q>","--since <ts>","--follow","--api-key <k>"] },
  { path: ["usage","utilization"], family: "cli-cost-usage", description: "", flags: ["--api-key <k>"] },
  { path: ["usage","history"], family: "cli-cost-usage", description: "", flags: ["--limit <n>"] },
  { path: ["usage","proxy-logs"], family: "cli-cost-usage", description: "", flags: ["--limit <n>"] },
  { path: ["pricing"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["pricing","sync"], family: "cli-cost-usage", description: "", flags: ["--provider <p>","--force"] },
  { path: ["pricing","list"], family: "cli-cost-usage", description: "", flags: ["--provider <p>","--model <m>","--limit <n>"] },
  { path: ["pricing","get <model>"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["pricing","defaults"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["pricing","defaults","show"], family: "cli-cost-usage", description: "", flags: [] },
  { path: ["pricing","defaults","set"], family: "cli-cost-usage", description: "", flags: ["--input <p>","--output <p>","--cache-read <p>","--cache-write <p>"] },
  { path: ["pricing","diff"], family: "cli-cost-usage", description: "", flags: ["--model <m>"] },
  { path: ["mcp"], family: "cli-mcp", description: "", flags: [] },
  { path: ["mcp","status"], family: "cli-mcp", description: "Show MCP server status", flags: ["--json"] },
  { path: ["mcp","restart"], family: "cli-mcp", description: "Restart the MCP server", flags: [] },
  { path: ["mcp","call <tool> [argsJson]"], family: "cli-mcp", description: "", flags: ["--args <json>","--args-file <path>","--stream","--scope <s>"] },
  { path: ["mcp","scopes"], family: "cli-mcp", description: "", flags: ["--tool <name>"] },
  { path: ["a2a"], family: "cli-a2a", description: "Agent-to-Agent (A2A) server", flags: [] },
  { path: ["a2a","status"], family: "cli-a2a", description: "Show A2A server status", flags: ["--json"] },
  { path: ["a2a","card"], family: "cli-a2a", description: "Print the Agent Card JSON", flags: [] },
  { path: ["a2a","skills"], family: "cli-a2a", description: "", flags: [] },
  { path: ["a2a","invoke <skill>"], family: "cli-a2a", description: "", flags: ["--input <json>","--input-file <path>","--wait","--timeout <ms>"] },
  { path: ["a2a","tasks"], family: "cli-a2a", description: "", flags: [] },
  { path: ["a2a","tasks","list"], family: "cli-a2a", description: "", flags: ["--status <s>","--skill <s>","--limit <n>","--since <ts>"] },
  { path: ["a2a","tasks","get <id>"], family: "cli-a2a", description: "", flags: [] },
  { path: ["a2a","tasks","cancel <id>"], family: "cli-a2a", description: "", flags: ["--yes"] },
  { path: ["a2a","tasks","watch <id>"], family: "cli-a2a", description: "", flags: [] },
  { path: ["a2a","tasks","stream <id>"], family: "cli-a2a", description: "", flags: [] },
  { path: ["a2a","tasks","logs <id>"], family: "cli-a2a", description: "", flags: [] },
  { path: ["tunnel"], family: "cli-tunnel", description: "", flags: [] },
  { path: ["tunnel","list"], family: "cli-tunnel", description: "", flags: ["--json"] },
  { path: ["tunnel","create [type]"], family: "cli-tunnel", description: "", flags: [] },
  { path: ["tunnel","stop <type>"], family: "cli-tunnel", description: "", flags: ["--yes"] },
  { path: ["tunnel","status <type>"], family: "cli-tunnel", description: "", flags: ["--json"] },
  { path: ["tunnel","logs <type>"], family: "cli-tunnel", description: "", flags: ["--tail <n>"] },
  { path: ["tunnel","info <type>"], family: "cli-tunnel", description: "", flags: ["--json"] },
  { path: ["tunnel","rotate <type>"], family: "cli-tunnel", description: "", flags: ["--yes"] },
  { path: ["backup"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["backup","create"], family: "cli-backup-sync", description: "", flags: ["--name <name>","--cloud","--encrypt","--key-file <path>","--exclude <pattern>","--retention <n>"] },
  { path: ["backup","auto"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["backup","auto","enable"], family: "cli-backup-sync", description: "", flags: ["--cron <expr>","--cloud","--encrypt","--retention <n>"] },
  { path: ["backup","auto","disable"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["backup","auto","status"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["restore [backupId]"], family: "cli-backup-sync", description: "", flags: ["--list","--yes"] },
  { path: ["sync"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["sync","push"], family: "cli-backup-sync", description: "", flags: ["--target <t>","--bundle <list>","--dry-run"] },
  { path: ["sync","pull"], family: "cli-backup-sync", description: "", flags: ["--source <s>","--merge","--replace","--dry-run"] },
  { path: ["sync","diff"], family: "cli-backup-sync", description: "", flags: ["--source <s>","--target <t>"] },
  { path: ["sync","bundle <outPath>"], family: "cli-backup-sync", description: "", flags: ["--include <list>"] },
  { path: ["sync","import <bundlePath>"], family: "cli-backup-sync", description: "", flags: ["--dry-run"] },
  { path: ["sync","initialize"], family: "cli-backup-sync", description: "", flags: ["--from-cloud"] },
  { path: ["sync","tokens"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["sync","tokens","list"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["sync","tokens","create"], family: "cli-backup-sync", description: "", flags: ["--name <n>","--scope <s>","--ttl <duration>"] },
  { path: ["sync","tokens","revoke <id>"], family: "cli-backup-sync", description: "", flags: ["--yes"] },
  { path: ["sync","status"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["sync","resolve"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","task"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","task"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","task"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","task","create"], family: "cli-backup-sync", description: "", flags: ["--title <t>","--prompt <p>","--prompt-file <path>","--repo <url>","--branch <b>","--metadata <json>"] },
  { path: ["cloud","devin","task","create"], family: "cli-backup-sync", description: "", flags: ["--title <t>","--prompt <p>","--prompt-file <path>","--repo <url>","--branch <b>","--metadata <json>"] },
  { path: ["cloud","jules","task","create"], family: "cli-backup-sync", description: "", flags: ["--title <t>","--prompt <p>","--prompt-file <path>","--repo <url>","--branch <b>","--metadata <json>"] },
  { path: ["cloud","codex","task","list"], family: "cli-backup-sync", description: "", flags: ["--status <s>","--limit <n>"] },
  { path: ["cloud","devin","task","list"], family: "cli-backup-sync", description: "", flags: ["--status <s>","--limit <n>"] },
  { path: ["cloud","jules","task","list"], family: "cli-backup-sync", description: "", flags: ["--status <s>","--limit <n>"] },
  { path: ["cloud","codex","task","get <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","task","get <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","task","get <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","task","status <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","task","status <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","task","status <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","task","cancel <taskId>"], family: "cli-backup-sync", description: "", flags: ["--yes"] },
  { path: ["cloud","devin","task","cancel <taskId>"], family: "cli-backup-sync", description: "", flags: ["--yes"] },
  { path: ["cloud","jules","task","cancel <taskId>"], family: "cli-backup-sync", description: "", flags: ["--yes"] },
  { path: ["cloud","codex","task","approve <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","task","approve <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","task","approve <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","task","message <taskId> <message>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","task","message <taskId> <message>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","task","message <taskId> <message>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","sources <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","devin","sources <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","jules","sources <taskId>"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","agents"], family: "cli-backup-sync", description: "", flags: [] },
  { path: ["cloud","codex","auth"], family: "cli-backup-sync", description: "", flags: ["--no-browser","--timeout <ms>"] },
  { path: ["cloud","devin","auth"], family: "cli-backup-sync", description: "", flags: ["--no-browser","--timeout <ms>"] },
  { path: ["cloud","jules","auth"], family: "cli-backup-sync", description: "", flags: ["--no-browser","--timeout <ms>"] },
  { path: ["audit"], family: "cli-policy-audit", description: "", flags: [] },
  { path: ["audit","tail"], family: "cli-policy-audit", description: "", flags: ["--source <s>","--follow","--limit <n>"] },
  { path: ["audit","search <query>"], family: "cli-policy-audit", description: "", flags: ["--source <s>","--since <ts>","--until <ts>","--limit <n>","--actor <id>","--action <a>"] },
  { path: ["audit","export <file>"], family: "cli-policy-audit", description: "", flags: ["--source <s>","--format <f>","--since <ts>","--until <ts>"] },
  { path: ["audit","stats"], family: "cli-policy-audit", description: "", flags: ["--source <s>","--period <p>"] },
  { path: ["audit","get <id>"], family: "cli-policy-audit", description: "", flags: ["--source <s>"] },
  { path: ["policy"], family: "cli-policy-audit", description: "", flags: [] },
  { path: ["policy","list"], family: "cli-policy-audit", description: "", flags: ["--kind <k>","--scope <s>"] },
  { path: ["policy","get <id>"], family: "cli-policy-audit", description: "", flags: [] },
  { path: ["policy","create"], family: "cli-policy-audit", description: "", flags: ["--file <path>"] },
  { path: ["policy","update <id>"], family: "cli-policy-audit", description: "", flags: ["--file <path>"] },
  { path: ["policy","delete <id>"], family: "cli-policy-audit", description: "", flags: ["--yes"] },
  { path: ["policy","evaluate"], family: "cli-policy-audit", description: "", flags: ["--api-key <k>","--action <a>","--resource <r>","--context <json>"] },
  { path: ["policy","export <file>"], family: "cli-policy-audit", description: "", flags: [] },
  { path: ["policy","import <file>"], family: "cli-policy-audit", description: "", flags: ["--overwrite"] },
  { path: ["logs"], family: "cli-policy-audit", description: "", flags: ["--follow","--filter <level>","--lines <n>","--timeout <ms>","--base-url <url>","--request-id <id>","--api-key <key>","--combo <name>","--status <code>","--duration-min <ms>","--duration-max <ms>","--export <path>"] },
  { path: ["telemetry"], family: "cli-policy-audit", description: "", flags: [] },
  { path: ["telemetry","summary"], family: "cli-policy-audit", description: "", flags: ["--period <p>","--compare-to <p>"] },
  { path: ["telemetry","export"], family: "cli-policy-audit", description: "", flags: ["--out <path>","--period <p>"] },
  { path: ["batches"], family: "cli-batches", description: "", flags: [] },
  { path: ["batches","list"], family: "cli-batches", description: "", flags: ["--status <s>","--limit <n>"] },
  { path: ["batches","get <batchId>"], family: "cli-batches", description: "", flags: [] },
  { path: ["batches","create"], family: "cli-batches", description: "", flags: ["--input-file <fileId>","--endpoint <e>","--completion-window <w>","--metadata <kv>"] },
  { path: ["batches","submit"], family: "cli-batches", description: "", flags: ["--jsonl <path>","--endpoint <e>","--wait"] },
  { path: ["batches","cancel <batchId>"], family: "cli-batches", description: "", flags: ["--yes"] },
  { path: ["batches","wait <batchId>"], family: "cli-batches", description: "", flags: ["--timeout <ms>"] },
  { path: ["batches","output <batchId>"], family: "cli-batches", description: "", flags: ["--out <path>"] },
  { path: ["batches","errors <batchId>"], family: "cli-batches", description: "", flags: ["--out <path>"] },
  { path: ["files"], family: "cli-batches", description: "", flags: [] },
  { path: ["files","list"], family: "cli-batches", description: "", flags: ["--purpose <p>","--limit <n>"] },
  { path: ["files","get <fileId>"], family: "cli-batches", description: "", flags: [] },
  { path: ["files","upload <path>"], family: "cli-batches", description: "", flags: ["--purpose <p>"] },
  { path: ["files","content <fileId>"], family: "cli-batches", description: "", flags: ["--out <path>"] },
  { path: ["files","delete <fileId>"], family: "cli-batches", description: "", flags: ["--yes"] },
  { path: ["eval"], family: "cli-eval", description: "", flags: [] },
  { path: ["eval","suites"], family: "cli-eval", description: "", flags: [] },
  { path: ["eval","suites","list"], family: "cli-eval", description: "", flags: [] },
  { path: ["eval","suites","get <suiteId>"], family: "cli-eval", description: "", flags: [] },
  { path: ["eval","suites","create"], family: "cli-eval", description: "", flags: ["--file <path>"] },
  { path: ["eval","run <suiteId>"], family: "cli-eval", description: "", flags: ["-m, --model <id>","--combo <name>","--concurrency <n>","--tag <tag>","--watch"] },
  { path: ["eval","list"], family: "cli-eval", description: "", flags: ["--suite <id>","--status <s>","--since <ts>","--limit <n>"] },
  { path: ["eval","get <runId>"], family: "cli-eval", description: "", flags: [] },
  { path: ["eval","results <runId>"], family: "cli-eval", description: "", flags: ["--failed"] },
  { path: ["eval","cancel <runId>"], family: "cli-eval", description: "", flags: ["--yes"] },
  { path: ["eval","scorecard <runId>"], family: "cli-eval", description: "", flags: [] },
  { path: ["simulate [prompt]"], family: "cli-eval", description: "", flags: ["--file <path>","-m, --model <id>","--combo <name>","--reasoning-effort <level>","--thinking-budget <n>","--explain"] },
  { path: ["skills","marketplace"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","marketplace","search [query]"], family: "cli-plugins-skills", description: "", flags: ["--category <c>","--tag <t>","--limit <n>","--sort <s>"] },
  { path: ["skills","marketplace","info <packageId>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","marketplace","install <packageId>"], family: "cli-plugins-skills", description: "", flags: ["--version <v>","--enable","--yes"] },
  { path: ["skills","marketplace","categories"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","marketplace","featured"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","list"], family: "cli-plugins-skills", description: "", flags: ["--type <type>","--enabled","--disabled","--api-key <key>"] },
  { path: ["skills","get <id>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","install"], family: "cli-plugins-skills", description: "", flags: ["--from-file <path>","--from-url <url>","--type <type>","--enable"] },
  { path: ["skills","enable <id>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","disable <id>"], family: "cli-plugins-skills", description: "", flags: ["--yes"] },
  { path: ["skills","delete <id>"], family: "cli-plugins-skills", description: "", flags: ["--yes"] },
  { path: ["skills","execute <id>"], family: "cli-plugins-skills", description: "", flags: ["--input <json>","--input-file <path>","--timeout <ms>"] },
  { path: ["skills","executions"], family: "cli-plugins-skills", description: "", flags: ["--skill <id>","--limit <n>","--status <s>"] },
  { path: ["skills","skillssh"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","skillssh","list"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["skills","skillssh","install <url>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin","list"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin","install <name>"], family: "cli-plugins-skills", description: "", flags: ["-y, --yes"] },
  { path: ["plugin","remove <name>"], family: "cli-plugins-skills", description: "", flags: ["-y, --yes"] },
  { path: ["plugin","info <name>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin","search [query]"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin","update [name]"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["plugin","scaffold <name>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["memory"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["memory","search <query>"], family: "cli-plugins-skills", description: "", flags: ["--type <type>","--limit <n>","--api-key <key>","--token-budget <n>"] },
  { path: ["memory","add"], family: "cli-plugins-skills", description: "", flags: ["--content <text>","--file <path>","--type <type>","--metadata <json>","--api-key <key>"] },
  { path: ["memory","clear"], family: "cli-plugins-skills", description: "", flags: ["--type <type>","--older-than <duration>","--api-key <key>","--yes"] },
  { path: ["memory","list"], family: "cli-plugins-skills", description: "", flags: ["--type <type>","--limit <n>","--api-key <key>"] },
  { path: ["memory","get <id>"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["memory","delete <id>"], family: "cli-plugins-skills", description: "", flags: ["--yes"] },
  { path: ["memory","health"], family: "cli-plugins-skills", description: "", flags: [] },
  { path: ["setup"], family: "cli-setup", description: "", flags: ["--password <value>","--add-provider","--provider <id>","--provider-name <name>","--api-key <value>","--default-model <model>","--provider-base-url <url>","--test-provider","--non-interactive","--list"] },
  { path: ["config"], family: "cli-setup", description: "Show or update CLI tool configuration", flags: [] },
  { path: ["config","list"], family: "cli-setup", description: "List all CLI tools and config status", flags: ["--json"] },
  { path: ["config","get <tool>"], family: "cli-setup", description: "Show current config for a tool", flags: ["--json"] },
  { path: ["config","set <tool>"], family: "cli-setup", description: "Write config for a tool", flags: ["--model <model>","--non-interactive","--yes","--allow-container-write"] },
  { path: ["config","validate <tool>"], family: "cli-setup", description: "Validate config format without writing", flags: ["--model <model>","--json"] },
  { path: ["config","opencode"], family: "cli-setup", description: "Generate OpenCode config (alias for 'config set opencode')", flags: ["--model <model>","--non-interactive","--yes","--allow-container-write"] },
  { path: ["config","lang"], family: "cli-setup", description: "", flags: [] },
  { path: ["config","lang","get"], family: "cli-setup", description: "", flags: ["--json"] },
  { path: ["config","lang","set <code>"], family: "cli-setup", description: "", flags: ["--force"] },
  { path: ["config","lang","list"], family: "cli-setup", description: "", flags: ["--json"] },
  { path: ["env"], family: "cli-setup", description: "Show and manage environment variables", flags: [] },
  { path: ["env","show"], family: "cli-setup", description: "Show current environment variables", flags: ["--json"] },
  { path: ["env","get <key>"], family: "cli-setup", description: "Get a single environment variable", flags: [] },
  { path: ["env","set <key> <value>"], family: "cli-setup", description: "Set an environment variable (current session only)", flags: [] },
  { path: ["update"], family: "cli-setup", description: "", flags: ["--check","--apply","--changelog","--dry-run","--no-backup","--yes"] },
  { path: ["autostart"], family: "cli-setup", description: "", flags: [] },
  { path: ["autostart","enable"], family: "cli-setup", description: "", flags: [] },
  { path: ["autostart","disable"], family: "cli-setup", description: "", flags: [] },
  { path: ["autostart","toggle"], family: "cli-setup", description: "", flags: [] },
  { path: ["autostart","status"], family: "cli-setup", description: "", flags: [] },
] as const satisfies readonly CliCapability[];

const CLI_SKILL_FAMILY_SET: ReadonlySet<string> = new Set(CLI_SKILL_FAMILIES);

export function assertCliCapabilityManifest(
  value: unknown
): asserts value is readonly CliCapability[] {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error("CLI capability manifest must be a non-empty array");
  }

  const paths = new Set<string>();
  for (const [index, entry] of value.entries()) {
    if (!entry || typeof entry !== "object") {
      throw new Error(`CLI capability manifest entry ${index} must be an object`);
    }
    const capability = entry as Partial<CliCapability>;
    if (!Array.isArray(capability.path) || capability.path.length === 0 ||
        capability.path.some((segment) => typeof segment !== "string" || segment.trim() !== segment || segment.length === 0)) {
      throw new Error(`CLI capability manifest entry ${index} has an invalid path`);
    }
    if (typeof capability.family !== "string" || !CLI_SKILL_FAMILY_SET.has(capability.family)) {
      throw new Error(`CLI capability manifest entry ${index} has an invalid family`);
    }
    if (typeof capability.description !== "string") {
      throw new Error(`CLI capability manifest entry ${index} has an invalid description`);
    }
    if (!Array.isArray(capability.flags) ||
        capability.flags.some((flag) => typeof flag !== "string" || flag.trim() !== flag || flag.length === 0)) {
      throw new Error(`CLI capability manifest entry ${index} has invalid flags`);
    }
    const renderedPath = capability.path.join(" ");
    if (paths.has(renderedPath)) {
      throw new Error(`CLI capability manifest contains duplicate path: ${renderedPath}`);
    }
    paths.add(renderedPath);
  }
}

