server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://shiguang-gateway-control:8788;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location /v1/ {
    proxy_pass http://shiguang-gateway-edge:8787;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location /live-ws {
    proxy_pass http://shiguang-gateway-realtime:20132;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
