export const AI_PROVIDERS: Record<string, { id: string; alias?: string; icon?: string; color?: string; passthroughModels?: boolean; hasFree?: boolean }>;
export const NOAUTH_PROVIDERS: Record<string, { id: string; alias?: string; [key: string]: unknown }>;
export const OAUTH_PROVIDERS: Record<string, unknown>;
export const APIKEY_PROVIDERS: Record<string, unknown>;
export const LOCAL_PROVIDERS: Record<string, unknown>;
export const UPSTREAM_PROXY_PROVIDERS: Record<string, unknown>;
export const WEB_COOKIE_PROVIDERS: Record<string, unknown>;
export const SEARCH_PROVIDERS: Record<string, unknown>;
export const AUDIO_ONLY_PROVIDERS: Record<string, unknown>;
export const CLOUD_AGENT_PROVIDERS: Record<string, unknown>;
export const IDE_PROVIDER_IDS: ReadonlySet<string>;
export const OPENAI_COMPATIBLE_PREFIX: string;
export const ANTHROPIC_COMPATIBLE_PREFIX: string;
export function getProviderConnectionFamilyIds(providerId: unknown): readonly string[];
export const USAGE_SUPPORTED_PROVIDERS: readonly string[];
export function isAnthropicCompatibleProvider(providerId: unknown): providerId is string;
export function isClaudeCodeCompatibleProvider(providerId: unknown): providerId is string;
export function isOpenAICompatibleProvider(providerId: unknown): providerId is string;
export function providerAllowsOptionalApiKey(providerId: unknown): boolean;
export function resolveProviderId(aliasOrId: string): string;
export function getProviderById(id: string): { id: string; alias?: string; [key: string]: unknown } | undefined;
export function getProviderByAlias(alias: string): { id: string; alias?: string; [key: string]: unknown } | null;
