export const AI_PROVIDERS: Record<string, { id: string; alias?: string; icon?: string; color?: string; passthroughModels?: boolean }>;
export const NOAUTH_PROVIDERS: Record<string, { id: string; alias?: string }>;
export const USAGE_SUPPORTED_PROVIDERS: readonly string[];
export function isAnthropicCompatibleProvider(providerId: unknown): providerId is string;
export function isClaudeCodeCompatibleProvider(providerId: unknown): providerId is string;
export function isOpenAICompatibleProvider(providerId: unknown): providerId is string;
export function providerAllowsOptionalApiKey(providerId: unknown): boolean;
export function resolveProviderId(aliasOrId: string): string;
export function getProviderById(id: string): { id: string; alias?: string; [key: string]: unknown } | undefined;
export function getProviderByAlias(alias: string): { id: string; alias?: string; [key: string]: unknown } | null;
