import type { z } from "zod";
export const createKeySchema: z.ZodTypeAny;
export const updateKeyPermissionsSchema: z.ZodTypeAny;
export const v1ImageUpscaleSchema: z.ZodTypeAny;
export const MemorySettingsExtendedSchema: z.ZodTypeAny;
export const createComboSchema: z.ZodTypeAny;
export const updateComboSchema: z.ZodTypeAny;
export const paginationSchema: z.ZodTypeAny;
export const toggleRateLimitSchema: z.ZodTypeAny;
export const versionManagerToolSchema: z.ZodTypeAny;
export const versionManagerInstallSchema: z.ZodTypeAny;
export const testProxySchema: z.ZodTypeAny;
export const databaseSettingsSchema: z.ZodObject<any>;
