import type { z } from "zod";
export const createKeySchema: z.ZodTypeAny;
export const createSyncTokenSchema: z.ZodTypeAny;
export const cloudSyncActionSchema: z.ZodTypeAny;
export const setBudgetSchema: z.ZodTypeAny;
export const updateKeyPermissionsSchema: z.ZodTypeAny;
export const v1ImageUpscaleSchema: z.ZodTypeAny;
export const MemorySettingsExtendedSchema: z.ZodTypeAny;
export const createComboSchema: z.ZodTypeAny;
export const updateComboSchema: z.ZodTypeAny;
export const updateComboDefaultsSchema: z.ZodTypeAny;
export const codexProfileNameSchema: z.ZodTypeAny;
export const codexProfileIdSchema: z.ZodTypeAny;
export const paginationSchema: z.ZodTypeAny;
export const toggleRateLimitSchema: z.ZodTypeAny;
export const updateResilienceSchema: z.ZodTypeAny;
export const versionManagerToolSchema: z.ZodTypeAny;
export const versionManagerInstallSchema: z.ZodTypeAny;
export const testProxySchema: z.ZodTypeAny;
export const updateProxyConfigSchema: z.ZodTypeAny;
export const databaseSettingsSchema: z.ZodObject<any>;
export const bulkImportProxiesSchema: z.ZodTypeAny;
export const bulkProxyAssignmentSchema: z.ZodTypeAny;
export const createProxyRegistrySchema: z.ZodTypeAny;
export const proxyAssignmentSchema: z.ZodTypeAny;
export const proxyPoolMemberSchema: z.ZodTypeAny;
export const proxyRotationStrategySchema: z.ZodTypeAny;
export const updateProxyRegistrySchema: z.ZodTypeAny;
export const jsonObjectSchema: z.ZodTypeAny;
export const resetStatsActionSchema: z.ZodTypeAny;
export const updateAutoDisableAccountsSchema: z.ZodTypeAny;
export const updateIpFilterSchema: z.ZodTypeAny;
export const updatePayloadRulesSchema: z.ZodTypeAny;
export const updateRequireLoginSchema: z.ZodTypeAny;
export const updateParamFilterConfigSchema: z.ZodTypeAny;
export const updateInterceptionRulesSchema: z.ZodTypeAny;
export const updateCcAliasSettingSchema: z.ZodTypeAny;
export const taskRoutingModelMapSchema: z.ZodTypeAny;
export const taskRoutingActionSchema: z.ZodTypeAny;
export const updateTaskRoutingSchema: z.ZodTypeAny;
export const oauthDeviceCompleteSchema: z.ZodTypeAny;
export const oauthExchangeSchema: z.ZodTypeAny;
export const oauthImportTokenSchema: z.ZodTypeAny;
export const oauthPollSchema: z.ZodTypeAny;
export const oauthPasteCredentialsSchema: z.ZodTypeAny;
export const cursorImportSchema: z.ZodTypeAny;
export const kiroApiKeyImportSchema: z.ZodTypeAny;
export const kiroImportSchema: z.ZodTypeAny;
export const traeImportSchema: z.ZodTypeAny;
export const cloudCredentialUpdateSchema: z.ZodTypeAny;
export const cloudResolveAliasSchema: z.ZodTypeAny;
export const cloudModelAliasUpdateSchema: z.ZodTypeAny;
export const volcenginePlanConnectSchema: z.ZodTypeAny;
export const volcenginePlanCodeSchema: z.ZodTypeAny;
export const volcenginePlanIdentitySchema: z.ZodTypeAny;
export const confirmedAccountSchema: z.ZodTypeAny;
export const zedImportSchema: z.ZodTypeAny;
export type ConfirmedAccount = {
  service: string;
  account: string;
  fingerprint: string;
};
