type OAuthContext = { params: Record<string, string> };
type OAuthHandler = (request: Request, context?: OAuthContext) => Promise<Response> | Response;
export const oauthFlowGet: OAuthHandler;
export const oauthFlowPost: OAuthHandler;
export const pasteCredentialsPost: OAuthHandler;
export const cliProxyImportGet: OAuthHandler;
export const cliProxyImportPost: OAuthHandler;
export const codexImportTokenPost: OAuthHandler;
export const codexImportPost: OAuthHandler;
export const cursorAutoImportGet: OAuthHandler;
export const cursorImportGet: OAuthHandler;
export const cursorImportPost: OAuthHandler;
export const cursorLoginCancelPost: OAuthHandler;
export const cursorLoginPollPost: OAuthHandler;
export const cursorLoginStartPost: OAuthHandler;
export const kiroApiKeyPost: OAuthHandler;
export const kiroAutoImportGet: OAuthHandler;
export const kiroImportPost: OAuthHandler;
export const kiroSocialAuthorizeGet: OAuthHandler;
export const kiroSocialExchangePost: OAuthHandler;
export const traeImportGet: OAuthHandler;
export const traeImportPost: OAuthHandler;
