export function listGroups(): any[];
export function createGroup(name: string): any;
export function renameGroup(id: string, name: string): any;
export function deleteGroup(id: string): boolean;
export function getGroup(id: string): any;
export function getPoolsByGroup(groupId: string): any[];
export function getApiKeyById(id: string): Promise<any>;
export function getCombos(): Promise<any[]>;
export function listProviderPlans(): any[];
export function getProviderPlan(connectionId: string): any;
export function upsertProviderPlan(connectionId: string, provider: string, dimensions: any[], source: string): any;
export function deleteProviderPlan(connectionId: string): boolean;
export function listPools(options?: { limit?: number; offset?: number }): { items: any[]; total: number };
export function createPool(data: any): any;
export function ensurePool(data: any): { pool: any; created: boolean; updated: boolean };
export function getPool(id: string): any;
export function updatePool(id: string, data: any): any;
export function deletePool(id: string): Promise<boolean>;
export function listConsumptionForPool(poolId: string, limit?: number): any[];
