export function getRadarCatalog(...args: any[]): any;
export function getRadarOffers(...args: any[]): any;
export function getRadarIntel(...args: any[]): any;
export function getRadarReferrals(...args: any[]): any;
export function syncRadar(...args: any[]): Promise<any>;
export function syncRadarReferrals(...args: any[]): Promise<any>;
export function shouldSyncReferralsOnRead(...args: any[]): boolean;
export function syncRadarOffers(...args: any[]): Promise<any>;
export function syncRadarIntel(...args: any[]): Promise<any>;
export function getRadarCache(...args: any[]): any;
export function getRadarSettings(...args: any[]): any;
export function setRadarOptIn(...args: any[]): any;
export function setRadarKey(...args: any[]): any;
export function getRadarReferralsCache(...args: any[]): any;
export function getRadarOffersCache(...args: any[]): any;
export function getRadarIntelCache(...args: any[]): any;
export function listRadarLocalModelState(...args: any[]): any;
export function setRadarLocalModelOverride(...args: any[]): any;
export function setRadarModelTombstone(...args: any[]): any;
export function clearRadarLocalModelOverride(...args: any[]): any;
export function getContributorClaimUrl(...args: any[]): string;
export function getSupporterPlansUrl(...args: any[]): string;
export function getRadarAdminUrl(...args: any[]): string | null;
export const SUPPORTER_KEY_REGEX: RegExp;
export function ensureRadarSyncScheduler(...args: any[]): any;
