import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Background, Controls, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { Alert, Button, Card, Checkbox, Descriptions, Drawer, Empty, Flex, Segmented, Select, Space, Statistic, Table, Tag, Typography, message } from "antd";
import { MaterialIcon } from "@/app/nav";
import { PageSkeleton } from "@/shared/components/PageSkeleton";
import { useI18n } from "@/i18n";
import { api } from "@/entities/api";
import { useLiveDashboard } from "@/entities/live";
import { loadOrchestrationHistory, loadOrchestrationInputs } from "./api";
import { buildOrchestrationSnapshot, projectOverview, type OrchestrationNode, type OrchestrationSource, type OrchestrationState } from "./model";

const stateColor:Record<OrchestrationState,string>={queued:"default",running:"processing",waiting_approval:"warning",succeeded:"success",failed:"error",cancelled:"default"};
function LiveRefresh(){const {tt}=useI18n();const client=useQueryClient();const {status,subscribe}=useLiveDashboard({channels:["agents"]});useEffect(()=>subscribe(event=>{if(event.channel==="agents"){void client.invalidateQueries({queryKey:["orchestration-snapshot"]});void client.invalidateQueries({queryKey:["orchestration-history"]});}}),[client,subscribe]);return status!=="open"?<Alert type="warning" showIcon message={tt("实时更新不可用，已保留轮询。","Live updates unavailable; polling remains active.")}/>:null;}
function flow(nodes:OrchestrationNode[],edges0:{id:string;from:string;to:string;active:boolean;kind:string}[]){
  const layer={orchestrator:0,source:150,work:330,overflow:330};
  const grouped=new Map<number,OrchestrationNode[]>();
  nodes.forEach(n=>{const y=layer[n.kind];grouped.set(y,[...(grouped.get(y)??[]),n])});
  const positions=new Map<string,{x:number;y:number}>();
  for(const [y,list] of grouped){list.sort((a,b)=>a.id.localeCompare(b.id));list.forEach((n,i)=>positions.set(n.id,{x:(i-(list.length-1)/2)*250,y}));}
  return {
    nodes:nodes.map(n=>({id:n.id,position:positions.get(n.id)!,data:{label:<Space orientation="vertical" size={2}><Typography.Text strong>{n.label}</Typography.Text>{n.state&&<Tag color={stateColor[n.state]}>{n.state}</Tag>}<Typography.Text type="secondary" style={{fontSize:11}}>{n.sublabel}</Typography.Text></Space>},style:{minWidth:180,borderRadius:10,border:n.state==="failed"?"1px solid var(--ant-color-error)":"1px solid var(--ant-color-border)",background:"var(--ant-color-bg-container)"}} satisfies Node)),
    edges:edges0.map(e=>({id:e.id,source:e.from,target:e.to,animated:e.active,style:{stroke:e.kind==="mirror"?"var(--ant-color-purple)":"var(--ant-color-primary)",strokeDasharray:e.kind==="mirror"?"6 4":undefined}} satisfies Edge)),
  };
}

export function OrchestrationPage(){const {tt}=useI18n();const [tab,setTab]=useState("agents");const [showCompleted,setShowCompleted]=useState(false);const [source,setSource]=useState<OrchestrationSource|"all">("all");const [selected,setSelected]=useState<OrchestrationNode|null>(null);const query=useQuery({queryKey:["orchestration-snapshot"],queryFn:loadOrchestrationInputs,refetchInterval:10_000});const history=useQuery({queryKey:["orchestration-history"],queryFn:loadOrchestrationHistory,enabled:tab==="history"});const repeat=useMutation({mutationFn:async(node:OrchestrationNode)=>{if(node.source==="conductor"){const id=node.id.slice("conductor:".length);const detail=await api<Record<string,unknown>>(`/conductor/tasks/${encodeURIComponent(id)}`);return api("/conductor/tasks",{method:"POST",body:JSON.stringify({repoUrl:detail.repo,prompt:detail.prompt,baseRef:detail.base_ref,mode:detail.mode})});}const input=node.raw?.input;if(!input||typeof input!=="object")throw new Error(tt("任务缺少可重复的输入","Task has no repeatable input"));return api("/a2a/tasks",{method:"POST",body:JSON.stringify(input)});},onSuccess:()=>message.success(tt("已创建重复任务","Repeated task created")),onError:(error:Error)=>message.error(error.message)});const snapshot=useMemo(()=>query.data?buildOrchestrationSnapshot(query.data,Date.now(),showCompleted):null,[query.data,showCompleted]);const filtered=useMemo(()=>{if(!snapshot)return null;if(source==="all")return snapshot;const ids=new Set(snapshot.nodes.filter(n=>n.id==="orchestrator"||n.source===source).map(n=>n.id));return {...snapshot,nodes:snapshot.nodes.filter(n=>ids.has(n.id)),edges:snapshot.edges.filter(e=>ids.has(e.from)&&ids.has(e.to))};},[snapshot,source]);const historyNodes=useMemo(()=>buildOrchestrationSnapshot({a2aTasks:history.data??[],sources:[{source:"a2a",ok:true}]},Date.now(),true).nodes.filter(n=>n.kind==="work"),[history.data]);const overview=snapshot?projectOverview(snapshot):null;if(query.isLoading)return <PageSkeleton/>;if(!snapshot)return <Alert type="error" message={query.error?.message??tt("编排快照不可用","Orchestration snapshot unavailable")}/>;const canvas=flow(filtered!.nodes,filtered!.edges);const works=snapshot.nodes.filter(n=>n.kind==="work");return <Flex vertical gap={12}>
  <LiveRefresh/><Card><Flex justify="space-between" align="center" wrap gap={12}><Space><MaterialIcon name="account_tree" size={30}/><div><Typography.Title level={4} style={{margin:0}}>{tt("统一编排画布","Unified orchestration canvas")}</Typography.Title><Typography.Text type="secondary">{tt("汇总云端智能体、A2A、Conductor 与模型组合的实时拓扑。","Live topology across Cloud Agents, A2A, Conductor and model routing.")}</Typography.Text></div></Space><Space wrap><Select value={source} onChange={setSource} style={{width:150}} options={[{value:"all",label:tt("全部来源","All sources")},{value:"cloud-agent",label:"Cloud Agents"},{value:"a2a",label:"A2A"},{value:"conductor",label:"Conductor"},{value:"routing",label:tt("路由","Routing")}]}/><Checkbox checked={showCompleted} onChange={e=>setShowCompleted(e.target.checked)}>{tt("显示旧终态任务","Show older completed")}</Checkbox></Space></Flex></Card>
  {snapshot.sources.filter(s=>!s.ok||s.offline).map(s=><Alert key={s.source} type={s.ok?"warning":"error"} showIcon message={`${s.source}: ${s.offline?tt("离线","offline"):s.error}`}/>) }
  <Segmented block value={tab} onChange={v=>setTab(String(v))} options={[{value:"agents",label:tt("智能体","Agents")},{value:"routing",label:tt("路由","Routing")},{value:"overview",label:tt("总览","Overview")},{value:"history",label:tt("历史","History")}]}/>
  {(tab==="agents"||tab==="routing")&&<Card styles={{body:{padding:0}}}><div style={{height:"min(68vh,720px)"}}><ReactFlow nodes={canvas.nodes.filter(n=>tab==="routing"?n.id==="orchestrator"||n.id.includes("routing"):!n.id.includes("routing"))} edges={canvas.edges.filter(e=>tab==="routing"?e.target.includes("routing")||e.source.includes("routing"):!e.target.includes("routing"))} fitView minZoom={0.15} maxZoom={1.8} nodesConnectable={false} onNodeClick={(_,node)=>setSelected(filtered!.nodes.find(n=>n.id===node.id)??null)} proOptions={{hideAttribution:true}}><Background/><Controls showInteractive={false}/></ReactFlow></div></Card>}
  {tab==="overview"&&<><Flex gap={12} wrap>{Object.entries(overview!).map(([key,value])=><Card key={key} style={{flex:"1 1 150px"}}><Statistic title={key.replace("_"," ")} value={value} valueStyle={{color:key==="failed"?"var(--ant-color-error)":undefined}}/></Card>)}</Flex><Card><Table rowKey="id" pagination={false} dataSource={works} onRow={row=>({onClick:()=>setSelected(row)})} columns={[{title:tt("任务","Task"),dataIndex:"label"},{title:tt("来源","Source"),dataIndex:"source",render:v=><Tag>{v}</Tag>},{title:tt("状态","State"),dataIndex:"state",render:v=><Tag color={stateColor[v as OrchestrationState]}>{v}</Tag>},{title:tt("更新时间","Updated"),dataIndex:"updatedAt",render:v=>v?new Date(v).toLocaleString():"—"}]}/></Card></>}
  {tab==="history"&&<Card loading={history.isLoading}>{historyNodes.length?<Table rowKey="id" dataSource={historyNodes} onRow={row=>({onClick:()=>setSelected(row)})} columns={[{title:tt("任务","Task"),dataIndex:"label"},{title:tt("来源","Source"),dataIndex:"source"},{title:tt("结果","Result"),dataIndex:"state",render:v=><Tag color={stateColor[v as OrchestrationState]}>{v}</Tag>},{title:tt("结束时间","Ended"),dataIndex:"endedAt",render:v=>v?new Date(v).toLocaleString():"—"}]}/>:<Empty description={tt("没有可显示的历史任务","No task history to display")}/>}</Card>}
  <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.label} width={520} extra={selected&&(selected.source==="a2a"||selected.source==="conductor")?<Button loading={repeat.isPending} onClick={()=>repeat.mutate(selected)}>{tt("重复执行","Repeat")}</Button>:null}>{selected&&<><Descriptions column={1} bordered items={[{key:"id",label:"ID",children:selected.id},{key:"source",label:tt("来源","Source"),children:selected.source},{key:"state",label:tt("状态","State"),children:selected.state},{key:"updated",label:tt("更新时间","Updated"),children:selected.updatedAt??"—"},{key:"memory",label:tt("记忆命中","Memory hits"),children:String((selected.raw?.memoryHits as unknown[]|undefined)?.length??selected.raw?.memory_hits??0)}]}/><Typography.Title level={5}>{tt("原始详情","Raw detail")}</Typography.Title><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",fontSize:12}}>{JSON.stringify(selected.raw??{},null,2)}</pre></>}</Drawer>
  </Flex>}
export default OrchestrationPage;
